configurable sessions expiration
hapifhir/org.hl7.fhir.core pull request #1501
Opened 2023-11-28 22:22 UTC by rpassas

### Summary

Original thread [here](https://chat.fhir.org/#narrow/stream/291844-FHIR-Validator). I didn't refactor SessionCache into an interface but I'm happy to do so while we're looking at it.

This is meant to be a simple addition to allow the [wrapper](https://github.com/hapifhir/org.hl7.fhir.validator-wrapper/pull/158) to create a `ValidationService` with a configurable `SessionCache`. That is, when `resetExpirationAfterAccess` is `true`, an active session's expiration time resets when it is accessed.

2023-11-29 20:37 UTC, dotasek commented
The implementation seems simple and reasonable, but I'd like to see a few things happen:

1. The new behaviour needs some unit tests. There are some already written that you can probably copy and alter to be appropriate: https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.validation/src/test/java/org/hl7/fhir/validation/cli/services/SessionCacheTest.java

2. I really would like SessionCache to be an interface, and for this to be a PassiveExpiringSessionCache implementation of that.

3. Could we make setExpirationAfterAccess fluent? So we can just call `SessionCache sessionCache = new SessionCache(...).setExpirationAfterAccess(true)`

2023-11-30 14:09 UTC, dotasek requested changes
See comments for requested changes.

2023-12-11 14:47 UTC, dotasek commented
Thank you for the refactor @rpassas. There is a failing test on Azure pipelines: https://dev.azure.com/fhir-pipelines/fhir-core-library/_build/results?buildId=16210&view=logs&j=7448d812-dbed-5970-799b-77d1cf827579&t=5ba38598-e9de-532c-87f1-57d0b28805df

I will investigate why that is, and review the test in the process.

I also see that the interface you created has methods that are directly bound to the expiring cache implementation. I'm going to create a branch that separates the two that can be merged into this.

2023-12-11 21:42 UTC, dotasek commented
@rpassas Please check these two branches.

https://github.com/hapifhir/org.hl7.fhir.core/tree/do-20231211-sessionCache-reset-on-fetch
https://github.com/hapifhir/org.hl7.fhir.validator-wrapper/tree/do-20231211-sessionCache-reset-on-fetch

Your test was nearly correct; I repaired it. I made some of the methods have more explicit meaning, and moved some methods to the implementation. Let me know if these changes work for you; I'd like to see them merged into your PRs before merging them to master/main.

2023-12-15 06:37 UTC, rpassas commented
> @rpassas Please check these two branches.
> 
> https://github.com/hapifhir/org.hl7.fhir.core/tree/do-20231211-sessionCache-reset-on-fetch https://github.com/hapifhir/org.hl7.fhir.validator-wrapper/tree/do-20231211-sessionCache-reset-on-fetch
> 
> Your test was nearly correct; I repaired it. I made some of the methods have more explicit meaning, and moved some methods to the implementation. Let me know if these changes work for you; I'd like to see them merged into your PRs before merging them to master/main.

I've merged your requested changes. They all look good to me - thanks!

2023-12-18 14:54 UTC, dotasek approved these changes

2023-12-18 14:54 UTC, merged