Fix problem with validation when StructureDefinition files contain ci…
hapifhir/org.hl7.fhir.core pull request #567
Opened 2021-08-04 08:28 UTC by jelmerterwal

…rcular dependencies

2021-08-05 07:53 UTC, jelmerterwal commented
@grahamegrieve it seems you did a lot of work on the file I changed. Could you perhaps have a look at this change?

2021-08-17 14:46 UTC, markiantorno requested changes
Please add unit tests for this, to verify it works and prevent this error from being re-introduced.
Also, update RELEASE_NOTES.md with details

2021-08-18 06:21 UTC, grahamegrieve reviewed
That's one impressive stack. But why are the dependencies circular? That sounds like a problem to me, and I'm not convinced it's a situation that we should handle differently.

2021-08-24 20:24 UTC, markiantorno commented
@jelmerterwal please follow up on this, and let us know if you need assistance.

2021-08-25 07:26 UTC, i-am-xhy commented
@jelmerterwal is unfortunately still on holiday untill monday. I'd expect him to react next week.

2021-08-25 07:29 UTC, grahamegrieve commented
if you add unit tests, add them to https://github.com/FHIR/fhir-test-cases (happy to help on how)

2021-09-01 12:01 UTC, jelmerterwal commented
@grahamegrieve and @markiantorno I've got no idea how to get a minimal failing test from this as I cannot oversee what is going on.

When I put a system out in the code like this (added to the first change in this PR);
```
        if (isGenerating(base) || isGenerating(derived)) {
            if (isGenerating(base)) {
                System.out.println("'base' already generating for '" + base.getUrl() + "'" + ", derived: " + derived.getUrl() + ", url: " + url + ", webUrl: " + webUrl);    
            } else {
                System.out.println("'derived' already generating for '" + derived.getUrl() + "'" + ", base: " + base.getUrl() + ", url: " + url + ", webUrl: " + webUrl);
            }
            
            // cancel snapshot generation early when we already process 'base' or 'derived'
            return;
        }
```

I get the following output for the test I added to my project for a custom profile;
```
'base' already generating for 'http://nictiz.nl/fhir/StructureDefinition/zib-Encounter', derived: http://nictiz.nl/fhir/StructureDefinition/gp-Encounter, url: , webUrl: null
'base' already generating for 'http://nictiz.nl/fhir/StructureDefinition/zib-Encounter', derived: http://nictiz.nl/fhir/StructureDefinition/gp-Encounter, url: , webUrl: null
'base' already generating for 'http://nictiz.nl/fhir/StructureDefinition/zib-Encounter', derived: http://nictiz.nl/fhir/StructureDefinition/gp-Encounter, url: , webUrl: null
Got the following messages
SingleValidationMessage[col=203,row=1,locationString=Observation.category[0],message=The system (http://hl7.org/fhir/observation-category) does not contain code (vital-signs) with display (Vital Signs),severity=warning]
SingleValidationMessage[col=211,row=1,locationString=Observation.category[0].coding[0],message=The system (http://hl7.org/fhir/observation-category) does not contain code (vital-signs) with display (null) for 'http://hl7.org/fhir/observation-category#vital-signs',severity=warning]
```

The profile I'm running this for is based on `zib-BloodPressure` and has (as far as I can see) the following related profiles that somehow cause the stacktrace when the fix has not been applied;

```
- zib-BloodPressure
base: zib-VitalSigns

- zib-VitalSigns
base: http://fhir.nl/fhir/StructureDefinition/nl-core-observation
	Observation.related.target: zib-VitalSigns (*) also a self reference

- nl-core-observation
base: Observation
	Observation.context: ..., zib-Encounter, gp-Encounter

- gp-Encounter
base: zib-Encounter

- zib-Encounter
base: Encounter
```

These profiles are mostly custom Dutch variants of the existing profiles `Observation` and `Encounter` from fhir dstu3.

To get the profiles and being able to validate I used yarn to retrieve the profiles from simplifier. After which I loaded the profiles in memory with a `PrePopulatedValidationSupport` for the test.

With a package.json containing the following dependencies;
```
  "dependencies": {
    "nictiz.fhir.nl.stu3.zib2017": "^2.1.5",
    "hl7.fhir.r3.core": "^3.0.2"
  }
```

This requires a registry in `.npmrc` that looks like the following;
```
registry=https://packages.simplifier.net
```

Also see https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/2.1.5

Hope you can aid me with adding an useful testcase here :)
If you require more context, please let me know.

2022-02-24 09:23 UTC, jelmerterwal commented
> @grahamegrieve and @markiantorno I've got no idea how to get a minimal failing test from this as I cannot oversee what is going on.

2022-09-05 06:13 UTC, closed without merging