Convertor refactor iii
hapifhir/org.hl7.fhir.core pull request #635
Opened 2021-10-29 17:49 UTC by dotasek

Refactor:

Move inner classes up one level.
Reorganize packages to account for class moves.
Add Lombok annotations where appropriate

2021-11-05 21:48 UTC, dotasek commented
The following pull requests address this refactor in downstream projects:

https://github.com/HL7/kindling/pull/45
https://github.com/HL7/fhir-ig-publisher/pull/332

2021-11-08 14:59 UTC, markiantorno approved these changes

2021-11-08 15:00 UTC, markiantorno requested changes
Update RELEASE_NOTES.md with the change and we're good to merge.

2021-11-08 17:00 UTC, dotasek commented
@markiantorno Release notes updated.

2021-11-08 17:06 UTC, merged