Resolve "677 - Enhance GraphQL Parser"
hapifhir/org.hl7.fhir.core pull request #678
Opened 2021-11-25 16:25 UTC by KevinDougan-SmileCDR

Closes #677

2021-11-26 18:14 UTC, markiantorno requested changes
Please update the RELEASE_NOTES.md file at the base project directory to include a note detailing the changes you have made here.

2021-11-26 18:14 UTC, markiantorno commented on org.hl7.fhir.utilities/src/test/java/org/hl7/fhir/utilities/graphql/GraphQLParserTests.java
> +  public void testParseMultipleIdValuesAndSelectSetWithIdAndFamilyGivenNames() throws IOException, EGraphQLException, EGraphEngine {
Please use the @DisplayName annotation from jupiter, so the name of the method isn't as huge

2021-11-26 18:14 UTC, markiantorno commented on org.hl7.fhir.utilities/src/test/java/org/hl7/fhir/utilities/graphql/GraphQLParserTests.java
> +    "{Patient (id:[1,2,3]){id,name{family,given}}}";
Can we put this in a separate file in the resources folder with an intelligent name of some kind.

2021-11-26 18:14 UTC, markiantorno commented on org.hl7.fhir.utilities/src/test/java/org/hl7/fhir/utilities/graphql/GraphQLParserTests.java
> +}
Let's split this test up. You're testing like 2-3 different things in one test (hence the massive name for it)

2021-11-30 03:01 UTC, grahamegrieve commented on org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/graphql/Parser.java
> +  protected Reader reader;
why these changes? If all you're doing is making something protected instead of private.. what is happening elsewhere?

2021-11-30 16:47 UTC, KevinDougan-SmileCDR commented
See Closing Comment here:
https://github.com/hapifhir/org.hl7.fhir.core/issues/677#issuecomment-982819433

2021-11-30 16:47 UTC, closed without merging